output_dir: ~/scratch/proteingym_output

summary:
  class: ProteinGym
  path: {{ datadir }}
  csv_file: DMS_substitutions.csv

structure_path: {{ structdir }}
surface_path: {{ surfdir }}

# id_list:      # If you only want to evaluate a subset of assays
#   - B2L11_HUMAN_Dutta_2010_binding-Mcl-1
#   - ADRB2_HUMAN_Jones_2020

#exclude_id_list:    # If you want to exclude some assays from evaluation
#   - BRCA2_HUMAN_Erwood_2022_HEK293T
#   - HIS7_YEAST_Pokusaeva_2019

dataset:
  class: DMSAssay
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: MutantStructure
        key: graph
        template_key: wild_type
      - class: ProteinView
        view: residue

task:
  class: ResidueTypePrediction
  mask_rate: 0.15
  dropout: 0.5
  plddt_threshold: 70
  model:
    class: FusionNetwork
    sequence_model:
      class: MyESM
      path: ~/scratch/protein-model-weights/esm-model-weights/
      model: ESM-2-650M
    structure_model:
      class: GVPGNN
      node_in_dim: [1280, 0]
      node_h_dim: [256, 16]
      edge_in_dim: [16, 1]
      edge_h_dim: [64, 1]
      num_layers: 5
      vector_gate: True
      readout: mean
      drop_rate: 0.1
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SpatialEdge
        radius: 10.0
        min_distance: 0
    edge_feature: null

gpus: [0]   # Only support single gpu inference now
batch_size: 4

model_checkpoint: {{ ckpt }}